import type { Product } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Artisan Ceramic Vase",
    description: "Handcrafted ceramic vase with organic curves and matte finish. Perfect for modern interiors.",
    price: 189,
    originalPrice: 249,
    category: "Home Decor",
    brand: "Studio Craft",
    images: ["/elegant-ceramic-vase-with-organic-curves.jpg", "/ceramic-vase-detail-shot.jpg", "/ceramic-vase-in-modern-interior.jpg"],
    rating: 4.8,
    reviewCount: 127,
    inStock: true,
    features: ["Handcrafted", "Food-safe glaze", "Unique texture", "Modern design"],
    specifications: {
      Material: "High-fired ceramic",
      Dimensions: '12" H x 8" W',
      Weight: "2.3 lbs",
      Care: "Hand wash recommended",
    },
    tags: ["ceramic", "handmade", "modern", "home-decor"],
  },
  {
    id: "2",
    name: "Minimalist Oak Desk",
    description: "Clean-lined oak desk with integrated cable management and soft-close drawers.",
    price: 899,
    category: "Furniture",
    brand: "Nordic Design",
    images: ["/minimalist-oak-desk-in-modern-office.jpg", "/oak-desk-drawer-detail.jpg", "/desk-cable-management-system.jpg"],
    rating: 4.9,
    reviewCount: 89,
    inStock: true,
    features: ["Solid oak construction", "Cable management", "Soft-close drawers", "Sustainable wood"],
    specifications: {
      Material: "Solid European oak",
      Dimensions: '60" W x 30" D x 29" H',
      Weight: "85 lbs",
      Finish: "Natural oil finish",
    },
    tags: ["furniture", "desk", "oak", "minimalist", "office"],
  },
  {
    id: "3",
    name: "Premium Wool Throw",
    description: "Luxuriously soft merino wool throw with subtle herringbone pattern.",
    price: 245,
    originalPrice: 320,
    category: "Textiles",
    brand: "Highland Weave",
    images: ["/luxury-wool-throw-with-herringbone-pattern.jpg", "/wool-throw-texture-close-up.jpg", "/throw-blanket-on-modern-sofa.jpg"],
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    features: ["100% merino wool", "Herringbone weave", "Machine washable", "Hypoallergenic"],
    specifications: {
      Material: "100% merino wool",
      Dimensions: '50" x 60"',
      Weight: "1.8 lbs",
      Care: "Machine wash cold, lay flat to dry",
    },
    tags: ["textiles", "wool", "throw", "luxury", "cozy"],
  },
  {
    id: "4",
    name: "Brass Table Lamp",
    description: "Sculptural brass table lamp with linen shade and dimmer switch.",
    price: 425,
    category: "Lighting",
    brand: "Lumina Studio",
    images: ["/sculptural-brass-table-lamp-with-linen-shade.jpg", "/brass-lamp-base-detail.jpg", "/table-lamp-ambient-lighting.jpg"],
    rating: 4.6,
    reviewCount: 156,
    inStock: false,
    features: ["Solid brass base", "Linen shade", "Dimmer switch", "LED compatible"],
    specifications: {
      Material: "Solid brass, linen shade",
      Dimensions: '24" H x 14" shade diameter',
      Weight: "6.2 lbs",
      Bulb: "E26 base, max 60W",
    },
    tags: ["lighting", "brass", "lamp", "sculptural", "modern"],
  },
  {
    id: "5",
    name: "Leather Lounge Chair",
    description: "Mid-century inspired lounge chair in premium full-grain leather.",
    price: 1299,
    originalPrice: 1599,
    category: "Furniture",
    brand: "Heritage Furniture",
    images: ["/mid-century-leather-lounge-chair.jpg", "/leather-chair-detail-stitching.jpg", "/lounge-chair-in-modern-living-room.jpg"],
    rating: 4.9,
    reviewCount: 78,
    inStock: true,
    features: ["Full-grain leather", "Hardwood frame", "High-density foam", "Swivel base"],
    specifications: {
      Material: "Full-grain leather, hardwood frame",
      Dimensions: '32" W x 34" D x 31" H',
      Weight: "65 lbs",
      "Seat Height": '17"',
    },
    tags: ["furniture", "chair", "leather", "mid-century", "lounge"],
  },
  {
    id: "6",
    name: "Ceramic Dinnerware Set",
    description: "Handmade ceramic dinnerware set for four with reactive glaze finish.",
    price: 189,
    category: "Tableware",
    brand: "Artisan Table",
    images: ["/handmade-ceramic-dinnerware-set.jpg", "/ceramic-plates-with-reactive-glaze.jpg", "/placeholder.svg?height=600&width=600"],
    rating: 4.5,
    reviewCount: 234,
    inStock: true,
    features: ["Handmade ceramic", "Reactive glaze", "Dishwasher safe", "Microwave safe"],
    specifications: {
      Material: "Stoneware ceramic",
      "Set Includes": "4 dinner plates, 4 salad plates, 4 bowls, 4 mugs",
      Dimensions: 'Dinner plate: 10.5" diameter',
      Care: "Dishwasher and microwave safe",
    },
    tags: ["tableware", "ceramic", "dinnerware", "handmade", "set"],
  },
]

export const categories = ["All Categories", "Home Decor", "Furniture", "Textiles", "Lighting", "Tableware"]

export const brands = [
  "All Brands",
  "Studio Craft",
  "Nordic Design",
  "Highland Weave",
  "Lumina Studio",
  "Heritage Furniture",
  "Artisan Table",
]
